services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file: ./backend/config/config.env.testing
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - type: bind
        source: ./backend/src
        target: /usr/app/backend/src
      - /usr/app/backend/node_modules

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - type: bind
        source: ./frontend/src
        target: /usr/app/frontend/src
      - /usr/app/frontend/node_modules

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mydb
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--username",
          "root",
          "--password",
          "example",
          "--eval",
          "db.adminCommand('ping')",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  mongo_data:
